name: Test All
on: [pull_request]
jobs:
  test-all:
    runs-on: ${{matrix.OS}}
    strategy:
      matrix:
        OS: [ubuntu-18.04, windows-2019]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - name: Unit tests
        run: sbt cli/test
        shell: bash
      - name: Intergration tests
        run: sbt cliIntegration/scripted
        shell: bash
