name: CI
on:
  pull_request:
    push:
    branches:
      - master
jobs:
  test-all:
    runs-on: ${{matrix.OS}}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - name: Unit tests
        run: sbt cli/test
      - name: Intergration tests
        run: sbt cliIntegration/scripted